# Generated by Django 3.2.7 on 2021-09-10 19:46

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorimodel',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterField(
            model_name='kategorimodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='isim', unique=True),
        ),
        migrations.CreateModel(
            name='YazilarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('icerik', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='baslik', unique=True)),
                ('resim', models.ImageField(upload_to='yazi_resimleri')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('duzenlenme_tarihi', models.DateTimeField(auto_now=True)),
                ('kategoriler', models.ManyToManyField(related_name='kategoriyazilari', to='blog.KategoriModel')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yazarinyazilari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yazı',
                'verbose_name_plural': 'Yazılar',
                'db_table': 'Yazi',
            },
        ),
    ]
