# Generated by Django 3.2.7 on 2021-09-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_iletisimmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yorummodel',
            old_name='guncellenme_tarihi',
            new_name='duzenlenme_tarihi',
        ),
    ]
